# You can split this configuration into multiple files, like this:
source = vars.conf
source = env.conf
source = autostart.conf
source = input.conf
source = keybinds.conf
source = monitors.conf
source = permissions.conf
source = layout.conf
source = look.conf
source = rules.conf
