$font = EB Garamond
$color1 = rgb(DA7890)
$color2 = rgb(C1B492)

general {
    hide_cursor = false
}

animations {
    enabled = false
}

background {
    path = /home/offeex/Pictures/wallpapers/void/fauux.png
}

# The Wired

image {
    path = /home/offeex/Downloads/wiredLogInNew.png
    rounding = 0
    border_size = 0
    position = 0, 25%
    size = 960
}

label {
    text = T  h  e      W  i  r  e  d      2  .  0  ‎
    color = $color2
    font_family = $font
    font_size = 48
}

shape {
    color = $color2
    size = 9.5%, 1
    position = 0, -2%
}

label {
    text = <span weight='bold'>⌈いとをひく⌋</span>
    color = $color2
    font_family = $font
    font_size = 20
    position = 0, -3.25%
}

# User ID

label {
    text = U   s   e   r      I   D   :
    color = $color2
    font_family = $font
    font_size = 20
    position = 0, -16.25%
}

shape {
    color = $color2
    size = 7.5%, 1.5%
    position = 0, -18%
}

label {
    text = $USER
    color = rgb(100, 100, 100)
    font_family = $font
    font_size = 20
    position = 0, -18%
}

# Password

label {
    text = P   a   s   s   W   o   r   d   :
    color = $color2
    font_family = $font
    font_size = 20
    position = 0, -20.25%
}

input-field {
    position = 0, -22%
    size = 7.5%, 1.5%
    outline_thickness = 0
    inner_color = $color2

    check_color = $color2
    fail_color = $color2
    swap_font_color = false

    font_color = rgb(100, 100, 100)
    fade_on_empty = false
    rounding = 0

    font_family = $font
    placeholder_text = ************
    fail_text = $PAMFAIL

    dots_text_format = <span baseline_shift='-36pt'>*</span>
    dots_size = 0.6
    dots_spacing = 0.4

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true
}


# Login button

shape {
    color = rgba(0, 0, 0, 0)
    size = 4%, 1.6%
    position = 0, -24.6%

    rounding = -1
    border_size = 2
    border_color = $color2

    onclick = wtype -P return -p return
}

label {
    text = L  o  g  i  n
    color = $color2
    font_family = $font
    font_size = 20
    position = 0, -24.6%
}

# Note

label {
    text = <span weight='bold'>N    O    T    E   :</span>
    color = $color1
    font_family = $font
    font_size = 14
    position = -12%, -39%
}

label {
    text = <span allow_breaks="true" letter_spacing='7000' line_height='0.8'>To login you have to have an invite from an existing<br/>user. There is no use in trying to beg, ask/request for<br/>an invite, we choose our new members with care.</span>
    color = $color2
    font_family = $font
    font_size = 14
    position = 40.5%, -88.5%
    halign = left
    valign = top
}

# Help and guidelines

label {
    text = <span letter_spacing='12000'>Help &amp; Guidelines</span>
    color = $color1
    font_family = $font
    font_size = 14
    position = 0, -45%
}
